[book]
authors = ["Joey Harrison <joeyh021@icloud.com>"]
language = "en"
multilingual = false
src = "src"
title = "RS118: UWCS Learns Rust"

[output.html]
git-repository-url = "https://github.com/joeyh021/rs118"

[output.html.fold]
enable = true
