[book]
authors = ["Joey Harrison <joeyh021@icloud.com>"]
language = "en"
multilingual = false
src = "src"
title = "RS118: UWCS Learns Rust"

[preprocessor.katex]

[output.html]
git-repository-url = "https://github.com/joeyh021/rs118"
preferred-dark-theme = "coal"
preferred-light-theme = "rust"

[output.html.fold]
enable = true
